import { readFile } from "node:fs/promises";
import { describe, expect, it } from "vitest";

describe("3DSTU FarmFlow deployment packaging", () => {
  it("runs the production image as a non-root app user with persistent data", async () => {
    const dockerfile = await readFile(new URL("../Dockerfile", import.meta.url), "utf8");
    const dockerignore = await readFile(new URL("../.dockerignore", import.meta.url), "utf8");
    const server = await readFile(new URL("./server.mjs", import.meta.url), "utf8");
    expect(dockerfile).toContain("FROM node:22-alpine AS build");
    expect(dockerfile).toContain("FROM node:22-alpine AS runtime");
    expect(dockerfile).toContain("npm ci --omit=dev");
    expect(dockerfile).toContain("COPY --chown=node:node api ./api");
    expect(dockerfile).toContain("COPY --chown=node:node --from=build /app/dist ./dist");
    expect(dockerfile).toContain("chown -R node:node /app /data");
    expect(dockerfile).toContain('VOLUME ["/data"]');
    expect(dockerfile).toContain("USER node");
    expect(dockerfile).toContain("process.env.LAYERPILOT_API_PORT||8797");
    expect(dockerignore).toContain("node_modules");
    expect(dockerignore).toContain("api/data");
    expect(dockerignore).toContain("api/storage");
    expect(dockerignore).toContain(".env");
    expect(dockerignore).toContain("!.env.example");
    expect(dockerignore).toContain("work");
    expect(dockerignore).toContain("deploy");
    expect(dockerignore).toContain("*.tgz");
    expect(dockerignore).toContain("layerpilot-support-*");
    expect(dockerignore).toContain("layerpilot-data-*");
    expect(dockerignore).toContain("layerpilot-pre-restore-*");
    expect(dockerignore).toContain("README.md");
    expect(server).toContain('process.once("SIGTERM"');
    expect(server).toContain("await server.close()");
  });

  it("exposes production compose settings and an environment template", async () => {
    const compose = await readFile(new URL("../docker-compose.yml", import.meta.url), "utf8");
    const envExample = await readFile(new URL("../.env.example", import.meta.url), "utf8");
    const packageJson = JSON.parse(await readFile(new URL("../package.json", import.meta.url), "utf8"));
    expect(compose).toContain("name: layerpilot");
    expect(compose).toContain("layerpilot-data:/data");
    expect(compose).toContain("${LAYERPILOT_BIND_ADDRESS:-127.0.0.1}:8797:8797");
    expect(compose).toContain("init: true");
    expect(compose).toContain("stop_grace_period: 30s");
    expect(compose).toContain("no-new-privileges:true");
    expect(compose).toContain("driver: json-file");
    expect(compose).toContain('max-size: "10m"');
    expect(compose).toContain('max-file: "5"');
    expect(compose).toContain("LAYERPILOT_DB_ADAPTER");
    expect(compose).toContain("LAYERPILOT_ADMIN_EMAIL");
    expect(compose).toContain("LAYERPILOT_ADMIN_PASSWORD");
    expect(compose).toContain("LAYERPILOT_DISABLE_DEFAULT_USERS");
    expect(compose).toContain("LAYERPILOT_DISABLE_DEMO_LOGIN");
    expect(compose).toContain("LAYERPILOT_METRICS_TOKEN");
    expect(compose).toContain("LAYERPILOT_OPS_EMAIL");
    expect(compose).toContain("LAYERPILOT_OPS_PASSWORD");
    expect(compose).toContain("layerpilot-worker");
    expect(compose).toContain("healthcheck:\n      disable: true");
    expect(compose).toContain("npm\", \"run\", \"worker");
    expect(compose).toContain("LAYERPILOT_ENABLE_INTERNAL_TELEMETRY");
    expect(compose).toContain("LAYERPILOT_ENABLE_INTERNAL_BRIDGE_POLLING");
    expect(compose).toContain("LAYERPILOT_API_INTERNAL_URL");
    expect(compose).toContain("LAYERPILOT_WORKER_TOKEN");
    expect(compose).toContain("CMD-SHELL");
    expect(envExample).toContain("LAYERPILOT_ADMIN_EMAIL=owner@example.com");
    expect(envExample).toContain("LAYERPILOT_PUBLIC_URL=http://127.0.0.1:8797");
    expect(envExample).toContain("LAYERPILOT_BIND_ADDRESS=127.0.0.1");
    expect(envExample).toContain("LAYERPILOT_DB_ADAPTER=json");
    expect(envExample).toContain("LAYERPILOT_DISABLE_DEFAULT_USERS=true");
    expect(envExample).toContain("LAYERPILOT_METRICS_TOKEN=change-this-metrics-token");
    expect(envExample).toContain("LAYERPILOT_OPS_EMAIL=");
    expect(envExample).toContain("LAYERPILOT_OPS_PASSWORD=");
    expect(envExample).toContain("LAYERPILOT_WORKER_TOKEN=change-this-worker-token");
    expect(envExample).toContain("LAYERPILOT_BACKUP_RETENTION_DAYS=30");
    expect(envExample).toContain("LAYERPILOT_PRE_RESTORE_BACKUP=true");
    expect(envExample).toContain("LAYERPILOT_DEPLOY_LOCK_DIR=/tmp/layerpilot-deploy.lock");
    expect(packageJson.scripts["package:ubuntu"]).toBe("node scripts/package-ubuntu.mjs package");
  });

  it("ships Ubuntu deployment helpers and reverse-proxy documentation", async () => {
    const script = await readFile(new URL("../scripts/ubuntu-deploy.sh", import.meta.url), "utf8");
    const backup = await readFile(new URL("../scripts/ubuntu-backup.sh", import.meta.url), "utf8");
    const opsCheck = await readFile(new URL("../scripts/ubuntu-ops-check.sh", import.meta.url), "utf8");
    const setup = await readFile(new URL("../scripts/ubuntu-setup.sh", import.meta.url), "utf8");
    const goLive = await readFile(new URL("../scripts/ubuntu-go-live-check.sh", import.meta.url), "utf8");
    const opsAuthCheck = await readFile(new URL("../scripts/ops-auth-check.mjs", import.meta.url), "utf8");
    const prodSmoke = await readFile(new URL("../scripts/prod-smoke.mjs", import.meta.url), "utf8");
    const packageScript = await readFile(new URL("../scripts/ubuntu-package.sh", import.meta.url), "utf8");
    const nodePackageScript = await readFile(new URL("../scripts/package-ubuntu.mjs", import.meta.url), "utf8");
    const supportBundle = await readFile(new URL("../scripts/ubuntu-support-bundle.sh", import.meta.url), "utf8");
    const guide = await readFile(new URL("../deploy/ubuntu/README.md", import.meta.url), "utf8");
    const nginx = await readFile(new URL("../deploy/ubuntu/nginx.layerpilot.conf", import.meta.url), "utf8");
    const dockerDaemon = await readFile(new URL("../deploy/ubuntu/docker-daemon.json", import.meta.url), "utf8");
    const backupService = await readFile(new URL("../deploy/ubuntu/layerpilot-backup.service", import.meta.url), "utf8");
    const backupTimer = await readFile(new URL("../deploy/ubuntu/layerpilot-backup.timer", import.meta.url), "utf8");
    const opsService = await readFile(new URL("../deploy/ubuntu/layerpilot-ops-check.service", import.meta.url), "utf8");
    const opsTimer = await readFile(new URL("../deploy/ubuntu/layerpilot-ops-check.timer", import.meta.url), "utf8");
    expect(script).toContain("docker compose");
    expect(script).toContain("docker compose version");
    expect(script).toContain("docker info");
    expect(script).toContain("Docker daemon is not reachable by the current user.");
    expect(script).toContain("newgrp docker");
    expect(script).toContain("sudo systemctl status docker");
    expect(script).toContain("init-env");
    expect(script).toContain("doctor");
    expect(script).toContain("update");
    expect(script).toContain("rollback");
    expect(script).toContain("fail_if_default_secret");
    expect(script).toContain("env_quote()");
    expect(script).toContain("write_env_line()");
    expect(script).toContain("Environment values must not contain newlines.");
    expect(script).toContain("app_url()");
    expect(script).toContain("check_env_file_permissions");
    expect(script).toContain("check_boolean_env");
    expect(script).toContain("check_number_env");
    expect(script).toContain("check_optional_url_env");
    expect(script).toContain("check_cors_origins_env");
    expect(script).toContain("check_optional_mqtt_url_env");
    expect(script).toContain("check_integration_env");
    expect(script).toContain("[ -f Dockerfile ]");
    expect(script).toContain("[ -f docker-compose.yml ]");
    expect(script).toContain("[ -f scripts/ubuntu-backup.sh ]");
    expect(script).toContain("[ -f scripts/ubuntu-ops-check.sh ]");
    expect(script).toContain("[ -f scripts/ubuntu-setup.sh ]");
    expect(script).toContain("[ -f scripts/ubuntu-go-live-check.sh ]");
    expect(script).toContain("[ -f scripts/ubuntu-package.sh ]");
    expect(script).toContain("[ -f deploy/ubuntu/nginx.layerpilot.conf ]");
    expect(script).toContain("[ -f deploy/ubuntu/docker-daemon.json ]");
    expect(script).toContain("[ -f deploy/ubuntu/layerpilot-ops-check.service ]");
    expect(script).toContain("[ -f deploy/ubuntu/layerpilot-ops-check.timer ]");
    expect(script).toContain("docker compose config");
    expect(script).toContain("LAYERPILOT_ADMIN_EMAIL");
    expect(script).toContain("curl-only smoke checks");
    expect(script).toContain("LAYERPILOT_WORKER_TOKEN");
    expect(script).toContain("LAYERPILOT_PUBLIC_URL");
    expect(script).toContain("LAYERPILOT_CORS_ORIGINS");
    expect(script).toContain("must not include wildcard origins in production");
    expect(script).toContain("write_env_line \"LAYERPILOT_ADMIN_PASSWORD\"");
    expect(script).toContain("write_env_line \"LAYERPILOT_CORS_ORIGINS\"");
    expect(script).toContain("write_env_line \"LAYERPILOT_OPS_EMAIL\"");
    expect(script).toContain("write_env_line \"LAYERPILOT_OPS_PASSWORD\"");
    expect(script).not.toContain("LAYERPILOT_ADMIN_PASSWORD=${LAYERPILOT_ADMIN_PASSWORD}");
    expect(script).toContain("LAYERPILOT_BIND_ADDRESS");
    expect(script).toContain("LAYERPILOT_OBJECT_STORAGE_PROVIDER must be local or s3");
    expect(script).toContain("LAYERPILOT_STRIPE_PRICE_STUDIO");
    expect(script).toContain("LAYERPILOT_MQTT_QOS must be 0, 1, or 2");
    expect(script).toContain("must start with mqtt:// or mqtts:// when set");
    expect(script).toContain("LAYERPILOT_BACKUP_RETENTION_DAYS");
    expect(script).toContain("check_boolean_env \"LAYERPILOT_PRE_RESTORE_BACKUP\"");
    expect(script).toContain("write_env_line \"LAYERPILOT_PRE_RESTORE_BACKUP\" \"true\"");
    expect(script).toContain("LAYERPILOT_DEPLOY_LOCK_DIR");
    expect(script).toContain("validate_deploy_lock_dir");
    expect(script).toContain("acquire_deploy_lock");
    expect(script).toContain("release_deploy_lock");
    expect(script).toContain("Another 3DSTU FarmFlow deploy/update/rollback appears to be running");
    expect(script).toContain("write_env_line \"LAYERPILOT_DEPLOY_LOCK_DIR\"");
    expect(script).toContain("base_url=\"$(app_url)\"");
    expect(script).toContain("update_deploy");
    expect(script).toContain("rollback_deploy");
    expect(script).toContain("latest_backup");
    expect(script).toContain("sed -n '1{s/^[^ ]* //;p;}'");
    expect(script).not.toContain("awk 'NR==1 {print $2}'");
    expect(script).toContain("Rollback requires an existing backup archive");
    expect(script).toContain("bash scripts/ubuntu-backup.sh restore \"$archive\"");
    expect(script).toContain("git pull --ff-only");
    expect(script).toContain("npm run qc");
    expect(script).toContain("scripts/ubuntu-backup.sh backup");
    expect(script).toContain("ops-check");
    expect(script).toContain("scripts/ubuntu-ops-check.sh");
    expect(script).toContain("support-bundle");
    expect(script).toContain("[ -f scripts/ubuntu-support-bundle.sh ]");
    expect(script).toContain("bash scripts/ubuntu-support-bundle.sh");
    expect(script).toMatch(/deploy\)[\s\S]*acquire_deploy_lock[\s\S]*deploy/);
    expect(script).toMatch(/update\)[\s\S]*acquire_deploy_lock[\s\S]*update_deploy/);
    expect(script).toMatch(/rollback\)[\s\S]*acquire_deploy_lock[\s\S]*rollback_deploy/);
    expect(script).toMatch(/deploy\(\) \{[\s\S]*doctor[\s\S]*compose up --build -d/);
    expect(backup).toContain("layerpilot_layerpilot-data");
    expect(backup).toContain("ENV_FILE=\"${LAYERPILOT_ENV_FILE:-.env}\"");
    expect(backup).toContain("load_env");
    expect(backup).toContain("LAYERPILOT_BACKUP_RETENTION_DAYS");
    expect(backup).toContain("LAYERPILOT_BACKUP_LOCK_DIR");
    expect(backup).toContain("LAYERPILOT_PRE_RESTORE_BACKUP");
    expect(backup).toContain("validate_lock_dir");
    expect(backup).toContain("LAYERPILOT_BACKUP_LOCK_DIR is unsafe");
    expect(backup).toContain("acquire_lock");
    expect(backup).toContain("release_lock");
    expect(backup).toContain("Another 3DSTU FarmFlow backup/restore operation appears to be running");
    expect(backup).toContain("verify_archive");
    expect(backup).toContain("scripts/ubuntu-backup.sh verify");
    expect(backup).toContain("scripts/ubuntu-backup.sh restore-drill");
    expect(backup).toContain("restore_drill");
    expect(backup).toContain("docker volume create \"$drill_volume\"");
    expect(backup).toContain("docker volume rm \"$drill_volume\"");
    expect(backup).toContain("test -f /data/layerpilot.db.json -o -f /data/layerpilot.sqlite");
    expect(backup).toContain("Restore drill passed");
    expect(backup).toContain("tar tzf \"$archive\"");
    expect(backup).toContain("Backup archive verified");
    expect(backup).toContain("prune_backups");
    expect(backup).toContain("pre_restore_backup_enabled");
    expect(backup).toContain("create_pre_restore_backup");
    expect(backup).toContain("layerpilot-pre-restore-");
    expect(backup).toContain("Pre-restore safeguard backup written");
    expect(backup).toContain("LAYERPILOT_ARCHIVE_NAME");
    expect(backup).toContain('tar xzf "/backup/$LAYERPILOT_ARCHIVE_NAME" -C /data');
    expect(backup).toContain("scripts/ubuntu-backup.sh restore");
    expect(backup).toContain("scripts/ubuntu-backup.sh prune");
    expect(backup).toContain("find \"$BACKUP_DIR\" -maxdepth 1 -type f -name 'layerpilot-data-*.tgz' -mtime +\"$RETENTION_DAYS\" -print -delete");
    expect(backup).toContain("find \"$BACKUP_DIR\" -maxdepth 1 -type f -name 'layerpilot-pre-restore-*.tgz' -mtime +\"$RETENTION_DAYS\" -print -delete");
    expect(backup).toContain("tar czf");
    expect(opsCheck).toContain("LAYERPILOT_MIN_FREE_MB");
    expect(opsCheck).toContain("ENV_FILE=\"${LAYERPILOT_ENV_FILE:-.env}\"");
    expect(opsCheck).toContain("load_env");
    expect(opsCheck).toContain("app_url()");
    expect(opsCheck).toContain("base_url=\"$(app_url)\"");
    expect(opsCheck).toContain("docker compose ps");
    expect(opsCheck).toContain("/api/readiness");
    expect(opsCheck).toContain("check_authenticated_api");
    expect(opsCheck).toContain("LAYERPILOT_OPS_EMAIL");
    expect(opsCheck).toContain("LAYERPILOT_OPS_PASSWORD");
    expect(opsCheck).toContain("node scripts/ops-auth-check.mjs");
    expect(opsCheck).toContain("docker compose exec -T -e LAYERPILOT_OPS_URL");
    expect(opsCheck).toContain("authenticated API, audit, and metrics checks passed");
    expect(opsCheck).toContain("sed -n '1{s/^[^ ]* //;p;}'");
    expect(opsCheck).toContain("layerpilot-backup.timer");
    expect(opsCheck).toContain("/etc/docker/daemon.json");
    expect(opsCheck).toContain("deploy/ubuntu/docker-daemon.json");
    expect(opsCheck).toContain("3DSTU FarmFlow ops check passed");
    expect(opsAuthCheck).toContain("LAYERPILOT_OPS_URL");
    expect(opsAuthCheck).toContain("/api/auth/login");
    expect(opsAuthCheck).toContain("/api/state");
    expect(opsAuthCheck).toContain("/api/audit?limit=5");
    expect(opsAuthCheck).toContain("/api/admin/integrity?checkStorage=true");
    expect(opsAuthCheck).toContain("storage.complete");
    expect(opsAuthCheck).toContain("/api/metrics");
    expect(opsAuthCheck).not.toContain("console.log(password");
    expect(prodSmoke).toContain("/api/admin/integrity?checkStorage=true");
    expect(prodSmoke).toContain("storage.complete");
    expect(setup).toContain("install-deps");
    expect(setup).toContain("install-firewall");
    expect(setup).toContain("install-log-rotation");
    expect(setup).toContain("install-backup-timer");
    expect(setup).toContain("install-ops-timer");
    expect(setup).toContain("install-nginx");
    expect(setup).toContain("install-https");
    expect(setup).toContain("check_boolean_env");
    expect(setup).toContain("LAYERPILOT_CERTBOT_STAGING\" \"$CERTBOT_STAGING");
    expect(setup).toContain("LAYERPILOT_OVERWRITE_DOCKER_DAEMON\" \"$OVERWRITE_DOCKER_DAEMON");
    expect(setup).toContain("must be true or false.");
    expect(setup).toContain("scripts/ubuntu-setup.sh all [your-domain.example] [owner@example.com]");
    expect(setup).toContain("curl is not installed yet; install-deps will install it before Docker setup.");
    expect(setup).toContain("configure_docker_group");
    expect(setup).toContain("sudo usermod -aG docker \"$target_user\"");
    expect(setup).toContain("newgrp docker");
    expect(setup).toContain("Domain names must be 253 characters or fewer.");
    expect(setup).toContain("Invalid domain label in $domain");
    expect(setup).toContain("Domain labels must not start or end with '-'.");
    expect(setup).toContain("[ \"${#label}\" -gt 63 ]");
    expect(setup).toContain("sed_escape_replacement");
    expect(setup).toContain("install_systemd_unit_template");
    expect(setup).toContain("sed \"s|/opt/layerpilot|$escaped_root|g\"");
    expect(setup).toContain("scripts/ubuntu-go-live-check.sh");
    expect(setup).toContain("scripts/ubuntu-package.sh");
    expect(setup).toContain("scripts/ubuntu-support-bundle.sh");
    expect(setup).toContain("LAYERPILOT_CERTBOT_EMAIL");
    expect(setup).toContain("LAYERPILOT_CERTBOT_STAGING");
    expect(setup).toContain("LAYERPILOT_OVERWRITE_DOCKER_DAEMON");
    expect(setup).toContain("sudo apt install -y ca-certificates curl git openssl ufw nginx");
    expect(setup).toContain("sudo ufw allow OpenSSH");
    expect(setup).toContain("sudo ufw allow 80/tcp");
    expect(setup).toContain("sudo ufw allow 443/tcp");
    expect(setup).toContain("sudo ufw --force enable");
    expect(setup).toContain("Port 8797 remains private behind Nginx");
    expect(setup).toContain("curl -fsSL https://get.docker.com | sudo sh");
    expect(setup).toContain("sudo install -m 0644 deploy/ubuntu/docker-daemon.json");
    expect(setup).toContain("install_systemd_unit_template deploy/ubuntu/layerpilot-backup.service");
    expect(setup).toContain("install_systemd_unit_template deploy/ubuntu/layerpilot-ops-check.service");
    expect(setup).toContain("sudo systemctl enable --now layerpilot-backup.timer");
    expect(setup).toContain("sudo systemctl enable --now layerpilot-ops-check.timer");
    expect(setup).toContain("sudo install -m 0644 deploy/ubuntu/nginx.layerpilot.conf");
    expect(setup).toContain("sudo nginx -t");
    expect(setup).toContain("sudo apt install -y certbot python3-certbot-nginx");
    expect(setup).toContain("sudo certbot --nginx -d \"$NGINX_DOMAIN\" --agree-tos --email \"$CERTBOT_EMAIL\" --redirect --non-interactive");
    expect(setup).toContain("systemctl list-timers certbot.timer");
    expect(setup).toMatch(/install_all\(\) \{[\s\S]*install_deps[\s\S]*install_firewall[\s\S]*install_log_rotation[\s\S]*install_backup_timer[\s\S]*install_ops_timer/);
    expect(setup).toMatch(/install_all\(\) \{[\s\S]*install_nginx[\s\S]*install_https/);
    expect(setup).toContain("Skipping HTTPS install because no Certbot email was provided.");
    expect(guide).toContain("Ubuntu 22.04 or 24.04");
    expect(guide).toContain("npm run package:ubuntu");
    expect(guide).toContain("node scripts/package-ubuntu.mjs package");
    expect(guide).toContain("bash scripts/ubuntu-package.sh package");
    expect(guide).toContain("bash scripts/ubuntu-package.sh verify");
    expect(guide).toContain("release/layerpilot-ubuntu-YYYYmmdd-HHMMSS.tgz.sha256");
    expect(guide).toContain("sha256sum -c layerpilot-ubuntu-YYYYmmdd-HHMMSS.tgz.sha256");
    expect(guide).toContain("Windows, macOS, Linux, or the Ubuntu server itself");
    expect(guide).toContain("release/layerpilot-ubuntu-YYYYmmdd-HHMMSS.tgz");
    expect(guide).toContain("local databases, uploaded files, `node_modules`, build outputs, support bundles, and backup archives are absent");
    expect(guide).toContain("bash scripts/ubuntu-setup.sh preflight");
    expect(guide).toContain("bash scripts/ubuntu-setup.sh all your-domain.example owner@example.com");
    expect(guide).toContain("installs base dependencies, firewall rules, Docker log rotation, timers, Nginx, and HTTPS");
    expect(guide).toContain("If you omit the email");
    expect(guide).toContain("bash scripts/ubuntu-setup.sh install-firewall");
    expect(guide).toContain("installs `curl` before Docker setup");
    expect(guide).toContain("adds the detected non-root deployment user to the `docker` group");
    expect(guide).toContain("does not expose port `8797`");
    expect(guide).toContain("bash scripts/ubuntu-setup.sh install-https your-domain.example owner@example.com");
    expect(guide).toContain("LAYERPILOT_CERTBOT_STAGING=true");
    expect(guide).toContain("certbot --nginx");
    expect(guide).toContain("DNS-safe hostname");
    expect(guide).toContain("labels of 1-63 characters");
    expect(guide).toContain("full domain must be 253 characters or fewer");
    expect(guide).toContain("LAYERPILOT_GO_LIVE_SUPPORT_ON_FAILURE=false");
    expect(guide).toContain("creates a redacted support bundle by default");
    expect(guide).toContain("extends proxy read/send timeouts");
    expect(guide).toContain("client_body_timeout 300s");
    expect(guide).toContain("bash scripts/ubuntu-setup.sh install-ops-timer");
    expect(guide).toContain("layerpilot-ops-check.timer");
    expect(guide).toContain("journalctl -u layerpilot-ops-check.service");
    expect(guide).toContain("LAYERPILOT_OVERWRITE_DOCKER_DAEMON");
    expect(guide).toContain("must be literal `true` or `false`");
    expect(guide).toContain("preflight stops on other values");
    expect(guide).toContain("scripts/ubuntu-deploy.sh deploy");
    expect(guide).toContain("`deploy`, `update`, and `rollback` use a directory lock");
    expect(guide).toContain("LAYERPILOT_DEPLOY_LOCK_DIR");
    expect(guide).toContain("/tmp/layerpilot-deploy.lock");
    expect(guide).toContain("scripts/ubuntu-deploy.sh update");
    expect(guide).toContain("scripts/ubuntu-deploy.sh rollback");
    expect(guide).toContain("scripts/ubuntu-deploy.sh ops-check");
    expect(guide).toContain("scripts/ubuntu-deploy.sh support-bundle");
    expect(guide).toContain("Support Bundle");
    expect(guide).toContain("scripts/ubuntu-support-bundle.sh");
    expect(guide).toContain("REDACTED");
    expect(guide).toContain("scripts/ubuntu-deploy.sh doctor");
    expect(guide).toContain("current-user access to the Docker daemon");
    expect(guide).toContain("run `newgrp docker` or reconnect");
    expect(guide).toContain("private `.env` permissions");
    expect(guide).toContain("non-default and minimum-length worker/metrics tokens");
    expect(guide).toContain("public/billing URL formats");
    expect(guide).toContain("S3 settings when object storage is enabled");
    expect(guide).toContain("Stripe price/webhook settings when billing is configured");
    expect(guide).toContain("MQTT URL/QoS/retain settings");
    expect(guide).toContain("required deployment files");
    expect(guide).toContain("LAYERPILOT_PUBLIC_URL");
    expect(guide).toContain("LAYERPILOT_BIND_ADDRESS=127.0.0.1");
    expect(guide).toContain("scripts/ubuntu-backup.sh backup");
    expect(guide).toContain("scripts/ubuntu-backup.sh verify");
    expect(guide).toContain("scripts/ubuntu-backup.sh restore-drill");
    expect(guide).toContain("verifies the newly written archive");
    expect(guide).toContain("temporary Docker volume");
    expect(guide).toContain("Run a restore drill periodically");
    expect(guide).toContain("verifies the archive before stopping services");
    expect(guide).toContain("scripts/ubuntu-backup.sh prune");
    expect(guide).toContain("renders the systemd unit with the current project path");
    expect(guide).toContain("update `WorkingDirectory` and `ExecStart`");
    expect(guide).toContain("LAYERPILOT_BACKUP_RETENTION_DAYS");
    expect(guide).toContain("LAYERPILOT_BACKUP_LOCK_DIR");
    expect(guide).toContain("LAYERPILOT_PRE_RESTORE_BACKUP");
    expect(guide).toContain("pre-restore safeguard backup");
    expect(guide).toContain("If no archive path is supplied");
    expect(guide).toContain("deploy/ubuntu/docker-daemon.json");
    expect(guide).toContain("per-service `json-file` log rotation");
    expect(guide).toContain("no-new-privileges");
    expect(guide).toContain("30-second graceful stop window");
    expect(guide).toContain("LAYERPILOT_MIN_FREE_MB");
    expect(guide).toContain("renders the ops-check systemd unit with the current project path");
    expect(guide).toContain("layerpilot_layerpilot-data");
    expect(guide).toContain("layerpilot-backup.timer");
    expect(guide).toContain("/var/backups/layerpilot");
    expect(guide).toContain("Certbot");
    expect(guide).toContain("layerpilot-data");
    expect(nginx).toContain("proxy_pass http://127.0.0.1:8797");
    expect(nginx).toContain("proxy_set_header Upgrade");
    expect(nginx).toContain("map $http_upgrade $layerpilot_connection_upgrade");
    expect(nginx).toContain("proxy_set_header Connection $layerpilot_connection_upgrade");
    expect(nginx).toContain("proxy_buffering off");
    expect(nginx).toContain("proxy_request_buffering off");
    expect(nginx).toContain("proxy_connect_timeout 60s");
    expect(nginx).toContain("proxy_read_timeout 3600");
    expect(nginx).toContain("proxy_send_timeout 3600");
    expect(nginx).toContain("X-Forwarded-Host");
    expect(nginx).toContain("X-Content-Type-Options nosniff");
    expect(nginx).toContain("X-Frame-Options SAMEORIGIN");
    expect(nginx).toContain("Permissions-Policy");
    expect(nginx).toContain("client_max_body_size 250m");
    expect(nginx).toContain("client_body_timeout 300s");
    expect(dockerDaemon).toContain('"log-driver": "json-file"');
    expect(dockerDaemon).toContain('"max-size": "10m"');
    expect(dockerDaemon).toContain('"max-file": "5"');
    expect(backupService).toContain("WorkingDirectory=/opt/layerpilot");
    expect(backupService).toContain("Requires=docker.service");
    expect(backupService).toContain("ExecStart=/usr/bin/env bash /opt/layerpilot/scripts/ubuntu-backup.sh backup");
    expect(backupService).toContain("LAYERPILOT_BACKUP_DIR=/var/backups/layerpilot");
    expect(backupService).toContain("LAYERPILOT_BACKUP_RETENTION_DAYS=30");
    expect(backupService).toContain("NoNewPrivileges=true");
    expect(backupService).toContain("PrivateTmp=true");
    expect(backupService).toContain("ProtectSystem=full");
    expect(backupService).toContain("TimeoutStartSec=30min");
    expect(backupTimer).toContain("OnCalendar=*-*-* 02:30:00");
    expect(backupTimer).toContain("Persistent=true");
    expect(backupTimer).toContain("Unit=layerpilot-backup.service");
    expect(opsService).toContain("WorkingDirectory=/opt/layerpilot");
    expect(opsService).toContain("ExecStart=/usr/bin/env bash /opt/layerpilot/scripts/ubuntu-ops-check.sh");
    expect(opsService).toContain("Requires=docker.service");
    expect(opsService).toContain("NoNewPrivileges=true");
    expect(opsService).toContain("PrivateTmp=true");
    expect(opsService).toContain("ProtectSystem=full");
    expect(opsService).toContain("TimeoutStartSec=5min");
    expect(opsService).toContain("LAYERPILOT_PUBLIC_URL=http://127.0.0.1:8797");
    expect(opsService).toContain("LAYERPILOT_MIN_FREE_MB=2048");
    expect(opsTimer).toContain("OnUnitActiveSec=15m");
    expect(opsTimer).toContain("Persistent=true");
    expect(opsTimer).toContain("Unit=layerpilot-ops-check.service");
    expect(goLive).toContain("3DSTU FarmFlow go-live check");
    expect(goLive).toContain("ENV_FILE=\"${LAYERPILOT_ENV_FILE:-.env}\"");
    expect(goLive).toContain("load_env");
    expect(goLive).toContain("LAYERPILOT_GO_LIVE_DEPLOY");
    expect(goLive).toContain("LAYERPILOT_GO_LIVE_QC");
    expect(goLive).toContain("LAYERPILOT_GO_LIVE_SUPPORT_ON_FAILURE");
    expect(goLive).toContain("check_boolean");
    expect(goLive).toContain("trap on_failure ERR");
    expect(goLive).toContain("3DSTU FarmFlow go-live check failed with exit code");
    expect(goLive).toContain("Creating support bundle for failed go-live check");
    expect(goLive).toContain("bash scripts/ubuntu-support-bundle.sh || true");
    expect(goLive).toContain("sed -n '1{s/^[^ ]* //;p;}'");
    expect(goLive).toContain("bash -n scripts/ubuntu-deploy.sh");
    expect(goLive).toContain("bash -n scripts/ubuntu-package.sh");
    expect(goLive).toContain("bash -n scripts/ubuntu-support-bundle.sh");
    expect(goLive).toContain("bash scripts/ubuntu-setup.sh preflight");
    expect(goLive).toContain("bash scripts/ubuntu-deploy.sh doctor");
    expect(goLive).toContain("npm run qc");
    expect(goLive).toContain("bash scripts/ubuntu-deploy.sh smoke");
    expect(goLive).toContain("bash scripts/ubuntu-backup.sh backup");
    expect(goLive).toContain("bash scripts/ubuntu-backup.sh restore-drill \"$archive\"");
    expect(goLive).toContain("bash scripts/ubuntu-deploy.sh ops-check");
    expect(packageScript).toContain("LAYERPILOT_PACKAGE_DIR");
    expect(packageScript).toContain("layerpilot-ubuntu-");
    expect(packageScript).toContain("verify_archive");
    expect(packageScript).toContain("write_checksum");
    expect(packageScript).toContain("verify_checksum_if_present");
    expect(packageScript).toContain("sha256sum -c");
    expect(packageScript).toContain(".sha256");
    expect(packageScript).toContain("package.json");
    expect(packageScript).toContain("api/server.mjs");
    expect(packageScript).toContain("scripts/ubuntu-deploy.sh");
    expect(packageScript).toContain("scripts/ubuntu-backup.sh");
    expect(packageScript).toContain("scripts/ops-auth-check.mjs");
    expect(packageScript).toContain("scripts/ubuntu-package.sh");
    expect(packageScript).toContain("scripts/package-ubuntu.mjs");
    expect(packageScript).toContain("scripts/ubuntu-support-bundle.sh");
    expect(packageScript).toContain("deploy/ubuntu/nginx.layerpilot.conf");
    expect(packageScript).toContain(".env.example");
    expect(packageScript).toContain("Release bundle contains forbidden local data");
    expect(packageScript).toContain("--exclude='api/data'");
    expect(packageScript).toContain("--exclude='api/storage'");
    expect(packageScript).toContain("--exclude='node_modules'");
    expect(packageScript).toContain("--exclude='.env'");
    expect(packageScript).not.toContain("--exclude='.env.*'");
    expect(packageScript).toContain("--exclude='*.tgz'");
    expect(nodePackageScript).toContain("LAYERPILOT_PACKAGE_DIR");
    expect(nodePackageScript).toContain("createHash");
    expect(nodePackageScript).toContain("writeChecksum");
    expect(nodePackageScript).toContain("verifyChecksumIfPresent");
    expect(nodePackageScript).toContain(".sha256");
    expect(nodePackageScript).toContain("spawn(\"tar\"");
    expect(nodePackageScript).toContain("layerpilot-ubuntu-");
    expect(nodePackageScript).toContain("verifyArchive");
    expect(nodePackageScript).toContain("scripts/ubuntu-deploy.sh");
    expect(nodePackageScript).toContain("scripts/ubuntu-backup.sh");
    expect(nodePackageScript).toContain("scripts/ubuntu-package.sh");
    expect(nodePackageScript).toContain("scripts/package-ubuntu.mjs");
    expect(nodePackageScript).toContain("scripts/ubuntu-support-bundle.sh");
    expect(nodePackageScript).toContain("deploy/ubuntu/nginx.layerpilot.conf");
    expect(nodePackageScript).toContain("\".env.example\"");
    expect(nodePackageScript).toContain("\".env\"");
    expect(nodePackageScript).not.toContain("\".env.*\"");
    expect(nodePackageScript).toContain("forbiddenMemberPattern");
    expect(nodePackageScript).toContain("Release bundle contains forbidden local data");
    expect(supportBundle).toContain("LAYERPILOT_SUPPORT_DIR");
    expect(supportBundle).toContain("redact_stream");
    expect(supportBundle).toContain("write_env_summary");
    expect(supportBundle).toContain("REDACTED");
    expect(supportBundle).toContain("docker compose logs --tail=200 layerpilot layerpilot-worker");
    expect(supportBundle).toContain("/api/health");
    expect(supportBundle).toContain("/api/readiness");
    expect(supportBundle).toContain("layerpilot-support-");
    expect(supportBundle).toContain("tar czf \"$bundle\"");
    expect(supportBundle).toContain("sed -n '1{s/^[^ ]* //;p;}'");
  });
});
