import { describe, expect, it } from "vitest";
import {
  buildModelChecks,
  buildPrusaSliceArgs,
  detectSlicerCommand,
  generatePrusaConfigIni,
  parseGcodeStats,
  runPrusaSlicePipeline,
  summarizeModelChecks
} from "./slicer-pipeline.mjs";

// 最小 STL：兩個三角面構成的退化但可讀的模型，fake slicer 不檢查幾何
const MINIMAL_STL = `solid test
facet normal 0 0 0
outer loop
vertex 0 0 0
vertex 10 0 0
vertex 0 10 0
endloop
endfacet
endsolid test
`;

const SAMPLE_GCODE = [
  "; generated by PrusaSlicer",
  "; total filament used [g] = 42.75",
  "; filament used [cm3] = 31.5",
  "; estimated printing time (normal mode) = 1d 2h 3m 4s",
  "M73 P0 R7200",
  "G28"
].join("\n");

describe("slicer pipeline", () => {
  it("detects explicit env override first", async () => {
    const result = await detectSlicerCommand({ LAYERPILOT_SLICER_CMD: "/opt/prusa-slicer" }, async () => null);
    expect(result.available).toBe(true);
    expect(result.command).toBe("/opt/prusa-slicer");
    expect(result.source).toBe("env:LAYERPILOT_SLICER_CMD");
  });

  it("probes PATH for prusa family before orca family", async () => {
    const probed = [];
    const found = await detectSlicerCommand({}, async (command) => {
      probed.push(command);
      return command === "prusa-slicer" ? "/usr/bin/prusa-slicer" : null;
    });
    expect(found.family).toBe("prusa");
    expect(probed[0]).toBe("prusa-slicer");

    const orca = await detectSlicerCommand({}, async (command) => (command === "orca-slicer" ? "/usr/bin/orca-slicer" : null));
    expect(orca.family).toBe("orca");

    const none = await detectSlicerCommand({}, async () => null);
    expect(none.available).toBe(false);
  });

  it("builds model checks with build volume fit and fail summary", () => {
    const checks = buildModelChecks(
      { dimensions: [400, 300, 200], triangleCount: 12, estimateGrams: 88, type: "STL" },
      { buildVolume: [256, 256, 256] }
    );
    expect(checks.find((check) => check.key === "build_volume").status).toBe("fail");
    const summary = summarizeModelChecks(checks);
    expect(summary.ok).toBe(false);

    const fine = buildModelChecks({ dimensions: [100, 50, 20], triangleCount: 5000, estimateGrams: 30, type: "3MF" }, { buildVolume: [256, 256, 256] });
    expect(summarizeModelChecks(fine).ok).toBe(true);
  });

  it("generates a prusa config ini honoring supports, infill, walls and material temps", () => {
    const ini = generatePrusaConfigIni({ material: "PETG", layerHeight: 0.28, infill: 40, walls: 3, supports: true });
    expect(ini).toContain("layer_height = 0.28");
    expect(ini).toContain("fill_density = 40%");
    expect(ini).toContain("perimeters = 3");
    expect(ini).toContain("support_material = 1");
    expect(ini).toContain("temperature = 240");
    const noSupport = generatePrusaConfigIni({ supports: false });
    expect(noSupport).toContain("support_material = 0");
  });

  it("builds prusa slice args with auto-orient, arrange and config load", () => {
    const args = buildPrusaSliceArgs({ inputPath: "/tmp/in.stl", outputPath: "/tmp/out.gcode", configPath: "/tmp/c.ini" });
    expect(args).toContain("--auto-orient");
    expect(args).toContain("--arrange");
    expect(args).toContain("--load");
    expect(args[args.length - 1]).toBe("/tmp/in.stl");
  });

  it("parses real grams and printing time from gcode", () => {
    const stats = parseGcodeStats(SAMPLE_GCODE);
    expect(stats.grams).toBe(42.75);
    // 1d 2h 3m 4s = 1563 分鐘左右
    expect(stats.minutes).toBe(24 * 60 + 2 * 60 + 3);
  });

  it("runs the full pipeline end to end against a fake slicer process", async () => {
    // 用 node 自己當「切片器」：驗證參數有傳進來、ini 存在、並產出含統計的 G-code
    const fakeSlicerScript = `
      const fs = require("node:fs");
      const args = process.argv.slice(1);
      const outIndex = args.indexOf("--output");
      const loadIndex = args.indexOf("--load");
      const inputIndex = args.findIndex((value, index) => index > 0 && fs.existsSync(value) && fs.statSync(value).isFile() && !value.endsWith(".ini"));
      if (outIndex === -1 || loadIndex === -1 || !args.includes("--auto-orient") || !args.includes("--arrange")) {
        console.error("missing expected flags"); process.exit(3);
      }
      const ini = fs.readFileSync(args[loadIndex + 1], "utf8");
      const grams = /support_material = 1/.test(ini) ? 21.5 : 18;
      fs.writeFileSync(args[outIndex + 1], "; total filament used [g] = " + grams + "\\n; estimated printing time (normal mode) = 45m 30s\\nM73 P0 R2730\\n");
      const stl = fs.readFileSync(args[inputIndex]);
      if (!stl.includes("solid test")) { console.error("input not passed"); process.exit(4); }
    `;
    const execImpl = async (command, args) =>
      import("node:child_process").then(({ execFile: ef }) => new Promise((resolve, reject) => ef(command, ["-e", fakeSlicerScript, "--", ...args], { windowsHide: true }, (error, stdout, stderr) => (error ? reject(Object.assign(error, { stderr })) : resolve({ stdout, stderr })))));

    const result = await runPrusaSlicePipeline({
      command: process.execPath,
      inputBuffer: Buffer.from(MINIMAL_STL),
      filename: "bracket.stl",
      settings: { material: "PLA", layerHeight: 0.2, infill: 15, walls: 2, supports: true },
      execImpl
    });
    expect(result.estimatedGrams).toBe(21.5);
    expect(result.estimatedMinutes).toBe(46); // 45m30s 四捨五入
    expect(result.autoOriented).toBe(true);
    expect(result.arranged).toBe(true);
    expect(Buffer.isBuffer(result.buffer)).toBe(true);
    expect(result.buffer.toString()).toContain("total filament used");
  });

  it("surfaces a clear error when the slicer fails without producing gcode", async () => {
    const execImpl = async () => {
      const error = new Error("exit code 3");
      throw error;
    };
    await expect(
      runPrusaSlicePipeline({ command: "prusa-slicer", inputBuffer: Buffer.from(MINIMAL_STL), settings: {}, execImpl })
    ).rejects.toThrow(/Slicer CLI failed/);
  });
});
